-- Creates new rows containing data in all named columns for the 'Authors' table --

INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Sofia', 'Smith', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Maria', 'Brown', 'Brazil');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Elena', 'Martin', 'Mexico');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Zoe', 'Roy', 'France');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Sebastian', 'Lavoie', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Dylan', 'Garcia', 'Spain');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Ian', 'Cruz', 'Mexico');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Lucas', 'Smith', 'USA');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Fabian', 'Wilson', 'USA');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Liam', 'Taylor', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('William', 'Thomas', 'Great Britain');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Logan', 'Moore', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Oliver', 'Martin', 'France');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Alysha', 'Thompson', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Isabelle', 'Lee', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Emily', 'Clark', 'USA');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('John', 'Young', 'China');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('David', 'Wright', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Thomas', 'Scott', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Helena', 'Adams', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Sofia', 'Carter', 'USA');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Liam', 'Parker', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Emily', 'Murphy', 'USA');


-- Creates new rows containing data in all named columns for the 'Books' table --

INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Build your database system', 1, 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('The red wall', 2 , 'Fiction');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('The perfect match', 3 , 'Fiction');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Digital Logic', 4 , 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('How to be a great lawyer', 5 , 'Law');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Manage successful negotiations', 6 , 'Society');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Pollution today', 7 , 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('A gray park', 2 , 'Fiction');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('How to be rich in one year', 8 , 'Humor');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Their bright fate', 9 , 'Fiction');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Black lines', 10 , 'Fiction');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('History of theater', 11 , 'Literature');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Electrical transformers', 12 , 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Build your big data system', 1 , 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Right and left', 13 , 'Children');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Programming using Python', 1 , 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Computer networks', 14 , 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Performance evaluation', 15 , 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Daily exercise', 16 , 'Well being');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('The silver uniform', 17 , 'Fiction');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Industrial revolution', 18 , 'History');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Green nature', 19 , 'Well being');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Perfect football', 20 , 'Well being');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('The chocolate love', 21 , 'Humor');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Director and leader', 22 , 'Society');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Play football every week', 20 , 'Well being');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Maya the bee', 13 , 'Children');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Perfect rugby', 20  , 'Well being');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('The end', 23  , 'Fiction');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Computer security', 1  , 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Participate', 22  , 'Society');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Positive figures', 3  , 'Fiction');

-- Creates new rows containing data in all named columns for the 'Clients' table --

INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Kaiden', 'Hill', 2006 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Alina', 'Morton', 2010  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Fania', 'Brooks', 1983  , 'Food Scientist');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Courtney', 'Jensen', 2006  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Brittany', 'Hill', 1984  , 'Firefighter');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Max', 'Rogers', 2005 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Margaret', 'McCarthy', 1981  , 'School Psychologist');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Julie', 'McCarthy', 1973 , 'Professor');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Ken', 'McCarthy', 1974  , 'Securities Clerk');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Britany', 'O"Quinn', 1984  , 'Violinist');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Conner', 'Gardner', 1998 , 'Licensed Massage Therapist');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Mya', 'Austin', 1960  , 'Parquet Floor Layer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Thierry', 'Rogers', 2004  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Eloise', 'Rogers', 1984  , 'Computer Security Manager');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Gerard', 'Jackson', 1979 , 'Oil Exploration Engineer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Randy', 'Day', 1986 , 'Aircraft Electrician');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Jodie', 'Page', 1990 , 'Manufacturing Director');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Coral', '	Rice', 1996 , 'Window Washer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Ayman', 'Austin', 2002 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Jaxson', 'Austin', 1999  , 'Repair Worker');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Joel', 'Austin', 1973  , 'Police Officer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Alina', 'Austin', 2010  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Elin', 'Austin', 1962 , 'Payroll Clerk');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Ophelia', 'Wolf', 2004 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Eliot', 'McGuire', 1967  , 'Dentist');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Peter', 'McKinney', 1968 , 'Professor');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Annabella', 'Henry', 1974 , 'Nurse');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Anastasia', '	Baker', 2001  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Tyler', 'Baker', 1984  , 'Police Officer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Lilian', 'Ross', 1983  , 'Insurance Agent');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Thierry', 'Arnold', 1975  , 'Bus Driver');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Angelina', 'Rowe', 1979 , 'Firefighter');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Marcia', 'Rowe', 1974  , 'Health Educator');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Martin', 'Rowe', 1976  , 'Ship Engineer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Adeline', 'Rowe', 2005  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Colette', 'Rowe', 1963  , 'Professor');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Diane', 'Clark', 1975  , 'Payroll Clerk');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Caroline', 'Clark', 1960 , 'Dentist');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Dalton', 'Clayton', 1982 , '	Police Officer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Steve', 'Clayton', 1990  , 'Bus Driver');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Melanie', 'Clayton', 1987  , 'Computer Engineer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Alana', 'Wilson', 2007 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Carson', 'Byrne', 1995 , '	Food Scientist');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Conrad', 'Byrne', 2007  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Ryan', '	Porter', 2008  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Elin', 'Porter', 1978  , 'Computer Programmer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Tyler', 'Harvey', 2007  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Arya', 'Harvey', 2008 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Serena', 'Harvey', 1978 , 'School Teacher');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Lilly', 'Franklin', 1976 , 'Doctor');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Mai', 'Franklin', 1994 , 'Dentist');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('John', 'Franklin', 1999 , 'Firefighter');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Judy', 'Franklin', 1995 , 'Firefighter');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Katy', '	Lloyd', 1992 , 'School Teacher');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Tamara', 'Allen', 1963 , 'Ship Engineer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Maxim', 'Lyons', 1985 , 'Police Officer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Allan', 'Lyons', 1983 , 'Computer Engineer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Marc', 'Harris', 1980 , 'School Teacher');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Elin', 'Young', 2009 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Diana', 'Young', 2008 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Diane', 'Young', 2006 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Alana', 'Bird', 2003  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Anna', 'Becker', 1979  , 'Security Agent');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Katie', 'Grant', 1977 , 'Manager');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Joan', 'Grant', 2010  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Bryan', 'Bell', 2001  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Belle', 'Miller', 1970  , 'Professor');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Peggy', 'Stevens', 1990  , 'Bus Driver');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Steve', 'Williamson', 1975 , 'HR Clerk');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Tyler', 'Williamson', 1999  , 'Doctor');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Izabelle', 'Williamson', 1990  , 'Systems Analyst');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Annabel', 'Williamson', 1960 , 'Cashier');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Mohamed', 'Waters', 1966 , 'Insurance Agent');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Marion', 'Newman', 1970  , 'Computer Programmer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Ada', 'Williams', 1986 , 'Computer Programmer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Sean', 'Scott', 1983  , 'Bus Driver');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Farrah', 'Scott', 1974  , 'Ship Engineer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Christine', 'Lambert', 1973 , 'School Teacher');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Alysha', 'Lambert', 2007  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Maia', 'Grant', 1984 , 'School Teacher');


-- Creates new rows containing data in all named columns for the 'Borrowers' table --


INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 35 , 17 , '2016-07-20' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 1 , 3 , '2017-04-19' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 42  , 8 , '2016-10-03' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 62 , 16 , '2016-04-05' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 53 , 13 , '2017-01-17' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 33 , 15 , '2015-11-26'  );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 40 , 14 , '2015-01-21' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 64 , 2 , '2017-09-10' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 56 , 30 , '2017-08-02' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 23 , 2 , '2018-06-28' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 46 , 19 , '2015-11-18' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 61 , 20 ,	'2015-11-24' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 58 , 7 , '2017-06-17' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 46 , 16 , '2017-02-12' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 80 , 21 , '2018-03-18' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 51 , 23 , '2015-09-01' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 49 , 18 ,	'2015-07-28' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 43 , 18 ,	'2015-11-04' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 30 , 2 ,	'2018-08-10' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 48 , 24 ,	'2015-05-13' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 71 , 5 ,	'2016-09-05' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 35 , 3 ,	'2016-07-03' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 57 , 1 ,	'2015-03-17' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 23 , 25 ,	'2017-08-16' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 20 , 12 ,	'2018-07-24' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 25 , 7 ,  '2015-01-31' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 72 , 29 , '2016-04-10' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 74 , 20 ,	'2017-07-31' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 53 , 14 ,	'2016-02-20' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 32 , 10 ,	'2017-07-24' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 12 , 15 ,	'2018-04-25' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 77 , 13 ,	'2017-06-09' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 30 , 4 ,	'2017-10-24' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 37 , 24 ,	'2016-01-14' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 27 ,	26 , '2017-06-05' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 1 , 16 , '2018-05-06' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 21 , 9 , '2016-03-19' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 69 , 28 ,	'2017-03-29' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 17 , 19 ,	'2017-03-14' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 8 , 9 , '2016-04-22' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 63 , 18 ,	'2015-01-25' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 65 , 20 ,	'2016-10-10' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 51 , 19 ,	'2015-07-28' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 23 , 12 ,	'2017-01-25' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 17 , 4 , '2017-04-18' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 68 , 5 , '2016-09-06' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 46 , 13 ,	'2017-09-30' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 15 , 13 ,	'2017-07-05' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 11 , 19 ,	'2017-12-14' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 78 , 15 ,	'2017-01-26' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 47 , 9 , '2015-03-03' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 68 , 7 , '2016-05-26' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 37 , 26 ,	'2017-02-06' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 48 , 27 ,	'2015-12-30' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 9 , 21 , '2017-10-21' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 29 , 8 , '2018-04-01' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 64 , 18 , '2017-08-29' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 61 , 26 ,	'2018-02-21' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 39 , 28 ,	'2016-07-26' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 73 , 18 ,	'2018-08-22' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 11 , 13 ,	'2018-01-17' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 45 , 6 , '2016-07-20' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 33 , 13 ,	'2018-03-18' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 10 , 17 , '2016-06-06' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 28 , 18 ,	'2017-02-17' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 51 , 3 , '2016-12-09' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 29 , 2 ,	'2015-09-18' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 28 , 30 ,	'2017-09-14' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 74, 20 , '2015-12-12' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 15 , 22 ,	'2015-01-14' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 57 , 8 ,	'2017-08-20' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 2 , 5 , '2015-01-18' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 74 , 12 ,	'2018-04-14' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 51 , 10 ,	'2016-02-25' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 25 , 17 ,	'2015-02-24' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 45 , 21 ,	'2017-02-10' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 27 , 25 ,	'2016-08-03' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 32 , 28 ,	'2016-06-15' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 71 , 21 ,	'2017-05-21' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 75 , 26 , '2016-05-03' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 56 , 32 ,	'2015-12-23' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 26 , 32 ,	'2015-05-16' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 66 , 32 ,	'2015-05-30' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 57 , 18 ,	'2017-09-15' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 40 , 15 ,	'2016-09-02' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 65 , 4 , '2017-08-17' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 54 , 7 , '2015-12-19' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 29 ,	4 ,	'2017-07-22' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 44 ,	9 ,	'2017-12-31' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 56 , 31 ,	'2015-06-13' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 17 , 4 , '2015-04-01' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 35 , 16 ,	'2018-07-19' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 22 , 18 ,	'2017-06-22' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 39 , 24 ,	'2015-05-29' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 63 , 14 ,	'2018-01-20' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 53 , 21 ,	'2016-07-31' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 40 , 9 , '2016-07-10' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 52 , 4 , '2017-04-05' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 27 , 20 ,	'2016-09-04' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 72 , 29 ,	'2015-12-06' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 49 , 16, 	'2017-12-19' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 6 , 12 ,	'2016-12-04' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 74 , 31 ,	'2016-07-27' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 48 , 32 ,	'2016-06-29' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 69 , 2 ,	'2016-12-27' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 60 , 32 ,	'2017-10-29' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 45 , 22 ,	'2017-06-12' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 42 , 15 ,	'2017-05-14' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 79 , 8 ,	'2016-10-13' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 70 , 18 ,	'2016-12-04' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 34 , 8 ,	'2016-03-06' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 43 , 8 ,	'2015-12-19' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 42 , 32 ,	'2016-04-20' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 67 , 5 ,	'2017-03-06' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 80 , 25 ,	'2015-06-23' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 54 , 11 ,	'2017-05-03' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 34 , 28 ,	'2017-08-30' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 65 , 20 ,	'2017-08-26' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 61 , 19 ,	'2018-01-05' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 38 , 12 ,	'2018-01-17' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 51 ,	4 ,	'2016-05-13' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 7 , 16 , '2016-03-17' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 46 , 16 , '2016-11-25' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 75 , 30 ,	'2018-08-12' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 72 , 32 , '2015-03-12' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 44 , 17 ,	'2015-06-15' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 68 , 15 ,	'2016-02-21' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 21 , 1 ,	'2016-06-19' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 14 , 25 ,	'2016-10-10' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 68 , 21 ,	'2016-05-27' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 35 , 20 ,	'2015-03-19' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 16 , 27 ,	'2016-08-08' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 79 , 31 ,	'2018-03-07' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 14 , 17 ,	'2018-04-28' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 29 , 28 ,	'2018-03-11' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 41 ,	4 ,	'2018-08-08' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 42 ,	3 ,	'2016-02-23' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 45 ,	3 ,	'2017-07-10' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 36 , 16 ,	'2018-07-19' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 36 , 30 ,	'2015-08-07' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 54 , 32 ,	'2018-03-14' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 61 , 15 ,	'2017-03-28' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 1 , 13 ,	'2018-05-17' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 43 , 1 ,	'2015-05-14' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 37 , 14 ,	'2015-07-30' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 62 , 17 ,	'2015-09-19' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 50 , 22 ,	'2016-12-02' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 45 , 1 ,	'2016-07-24' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 32 , 17 ,	'2018-03-10' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 13 , 28 ,	'2016-02-14' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 15 ,	9 ,	'2018-08-11' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 10 , 19 , '2018-08-29' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 66 , 3 ,	'2016-11-27' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 68 , 29 ,	'2017-07-12' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 21 , 14 ,	'2018-06-27' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 35 , 9 ,	'2016-01-22' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 17 , 24 ,	'2016-08-25' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 40 , 21 ,	'2015-07-09' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 1 , 24 ,	'2016-03-28' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 70 , 27 ,	'2015-07-10' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 80 , 26 ,	'2016-04-24' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 29 ,	5 ,	'2015-10-18' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 76 ,	12 , '2018-04-25' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 22 ,	4 ,	'2016-12-24' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 2 , 2 , '2017-10-26' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 35 , 13 ,	'2016-02-28' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 40 , 8 ,	'2017-10-02' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 68 , 9 ,	'2016-01-03' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 32 , 5 ,	'2016-11-13' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 34 , 17 ,	'2016-09-15' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 34 , 16 ,	'2018-04-13' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 80 , 30 ,	'2016-10-13' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 20 , 32 ,	'2015-11-17' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 36 , 10 ,	'2017-09-01' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 78 , 12 ,	'2018-06-27' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 57 , 8 ,	'2016-03-22' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 75 , 11 ,	'2017-06-27' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 71 , 10 ,	'2015-08-01' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 48 , 22 ,	'2015-09-29' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 19 , 16 ,	'2016-02-21' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 79 , 30 ,	'2018-08-20' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 70 , 13 ,	'2016-09-16' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 30 , 6 ,	'2017-02-10' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 45 , 12 ,	'2017-10-12' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 30 , 27 ,	'2016-11-23' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 26 , 3 ,	'2016-08-13' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 66 , 6 ,	'2017-01-14' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 47 , 15 ,	'2016-02-10' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 53 , 30 ,	'2018-08-08' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 80 , 16 ,	'2016-03-31' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 70 , 13 ,	'2018-02-03' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 14 , 25 ,	'2016-03-27' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 46 , 22 ,	'2016-01-13' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 30 , 32 ,	'2015-08-06' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 60 , 14 ,	'2016-11-27' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 14 , 13 ,	'2018-05-23' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 71 , 15 ,	'2016-06-22' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 38 , 21 ,	'2015-12-27' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 69 , 30 ,	'2017-04-29' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 49 , 31 ,	'2018-06-03' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 28 , 28 ,	'2015-05-29' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 49 ,	3 ,	'2016-08-30' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 75 , 1 ,	'2015-10-29' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 78 , 3 ,	'2017-05-12' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 43 , 18 ,	'2015-03-25' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 27 , 21 ,	'2016-02-22' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 64 , 22 ,	'2015-04-03' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 21 , 11 ,	'2017-12-09' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 66 , 29 ,	'2016-12-20' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 45 , 13 ,	'2017-04-15' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 48 , 30 ,	'2015-01-31' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 20 , 25 ,	'2017-12-20' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 41 , 20 ,	'2018-01-29' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 51 , 12 , '2015-07-05' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 5 , 1 ,  '2015-04-12' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 40 , 3 ,	'2018-02-24' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 79 , 4 ,	'2018-06-27' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 15 , 10 ,	'2016-11-01' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 42 , 22 ,	'2016-12-28' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 17 , 9 ,	'2018-01-29' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 38 , 13 ,	'2016-05-09' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 79 , 2 ,	'2017-12-06' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 74 , 3 ,	'2015-12-07' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 46 , 8 ,	'2016-06-05' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 78 , 22 ,	'2018-08-11' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 45 , 2 ,	'2015-04-20' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 72 , 31 ,	'2015-11-11' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 18 , 17 ,	'2015-03-21' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 29 , 3 ,	'2017-08-13' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 66 , 11 ,	'2018-06-05' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 36 , 16 ,	'2016-04-28' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 26 , 2 ,	'2016-10-23' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 32 , 1 ,	'2017-10-31' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 62 , 14 ,	'2017-07-25' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 12 ,	4 ,	'2015-07-08' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 38 ,	32 , '2015-02-24' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 29 , 16 ,	'2016-07-28' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 36 , 25 ,	'2017-05-07' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 76 ,	7 ,	'2015-06-13' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 28 , 16 ,	'2016-08-15' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 60 , 13 ,	'2016-08-26' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 8 , 3 , '2017-07-28' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 25 , 1 ,	'2016-07-30' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 62 , 29 ,	'2018-08-24' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 51 , 8 ,	'2016-09-01' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 27 , 23 ,	'2015-02-08' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 69 , 12 ,	'2018-06-25' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 51 , 12 ,	'2015-07-04' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 7 , 4 ,	'2015-05-01' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 31 , 15 ,	'2017-10-29' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 14 , 23 ,	'2015-01-15' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 14 ,	1 ,	'2018-05-21' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 39 ,	25 , '2015-12-26' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 79 , 24 ,	'2016-05-31' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 40 ,	15 , '2016-03-18' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 51 , 13 ,	'2018-04-13' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 61 , 1 , 	'2015-02-11' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 15 , 24 ,	'2018-03-02' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 10 , 22 ,	'2018-01-21' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 67 , 10 ,	'2017-07-08' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 79 , 11 ,	'2016-12-11' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 19 , 32 ,	'2016-05-04' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 35 , 11 ,	'2017-08-01' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 27 , 13 ,	'2017-12-15' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 30 , 22 ,	'2015-12-22' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 8 , 7 , '2015-06-26' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 70 , 9 ,	'2016-03-20' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 56 , 18 ,	'2016-01-29' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 13 , 19 ,	'2015-03-06' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 61 , 2 ,	'2016-06-18' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 47 , 13 ,	'2017-09-18' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 30 , 22 ,	'2016-02-19' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 18 , 22 ,	'2016-12-31' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 34 , 29 ,	'2017-10-27' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 32 , 21 ,	'2015-06-03' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 9 , 28 ,	'2016-03-30' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 62 , 24 ,	'2015-03-23' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 44 , 22 ,	'2017-04-29' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 27 , 5 ,	'2015-03-25' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 61 , 28 ,	'2017-07-14' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 5 , 13 ,	'2016-12-04' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 43 , 19 ,	'2018-03-15' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 34 , 19 ,	'2016-06-05' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 35 ,	5 ,	'2018-02-19' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 13 , 12 ,	'2016-09-23' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 74 , 18 ,	'2016-12-26' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 70 , 31 ,	'2017-08-15' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 42 , 17 ,	'2016-06-15' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 51 , 24 ,	'2018-07-30' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 45 , 30 ,	'2015-01-15' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 70 , 17 ,	'2017-10-07' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 77 , 7 ,	'2017-01-06' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 74 , 25 ,	'2015-09-25' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 47 , 14 ,	'2018-02-01' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 10 , 2 ,	'2017-04-18' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 16, 21 , '2016-10-03' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 48 , 5 ,	'2016-09-17' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 72 , 3 ,	'2017-02-10' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 26 , 23 ,	'2016-03-01' );
INSERT INTO Borrowers (ClientID, BookID, BorrowDate) values ( 49 , 23 ,	'2016-10-25' );

