-- Creates new rows containing data in all named columns for the 'Authors' table --

INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Sofia', 'Smith', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Maria', 'Brown', 'Brazil');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Elena', 'Martin', 'Mexico');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Zoe', 'Roy', 'France');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Sebastian', 'Lavoie', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Dylan', 'Garcia', 'Spain');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Ian', 'Cruz', 'Mexico');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Lucas', 'Smith', 'USA');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Fabian', 'Wilson', 'USA');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Liam', 'Taylor', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('William', 'Thomas', 'Great Britain');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Logan', 'Moore', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Oliver', 'Martin', 'France');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Alysha', 'Thompson', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Isabelle', 'Lee', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Emily', 'Clark', 'USA');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('John', 'Young', 'China');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('David', 'Wright', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Thomas', 'Scott', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Helena', 'Adams', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Sofia', 'Carter', 'USA');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Liam', 'Parker', 'Canada');
INSERT INTO Authors (AuthorFirstName, AuthorLastName, AuthorNationality) values ('Emily', 'Murphy', 'USA');


-- Creates new rows containing data in all named columns for the 'Books' table --

INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Build your database system', 1, 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('The red wall', 2 , 'Fiction');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('The perfect match', 3 , 'Fiction');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Digital Logic', 4 , 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('How to be a great lawyer', 5 , 'Law');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Manage successful negotiations', 6 , 'Society');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Pollution today', 7 , 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('A gray park', 2 , 'Fiction');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('How to be rich in one year', 8 , 'Humor');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Their bright fate', 9 , 'Fiction');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Black lines', 10 , 'Fiction');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('History of theater', 11 , 'Literature');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Electrical transformers', 12 , 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Build your big data system', 1 , 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Right and left', 13 , 'Children');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Programming using Python', 1 , 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Computer networks', 14 , 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Performance evaluation', 15 , 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Daily exercise', 16 , 'Well being');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('The silver uniform', 17 , 'Fiction');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Industrial revolution', 18 , 'History');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Green nature', 19 , 'Well being');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Perfect football', 20 , 'Well being');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('The chocolate love', 21 , 'Humor');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Director and leader', 22 , 'Society');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Play football every week', 20 , 'Well being');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Maya the bee', 13 , 'Children');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Perfect rugby', 20  , 'Well being');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('The end', 23  , 'Fiction');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Computer security', 1  , 'Science');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Participate', 22  , 'Society');
INSERT INTO Books (BookTitle, AuthorID, Genre) values ('Positive figures', 3  , 'Fiction');

-- Creates new rows containing data in all named columns for the 'Clients' table --

INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Kaiden', 'Hill', 2006 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Alina', 'Morton', 2010  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Fania', 'Brooks', 1983  , 'Food Scientist');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Courtney', 'Jensen', 2006  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Brittany', 'Hill',  , 'Firefighter');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Max', 'Rogers', 2005 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Margaret', 'McCarthy', 1981  , 'School Psychologist');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Julie', 'McCarthy', 1973 , 'Professor');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Ken', 'McCarthy', 1974  , 'Securities Clerk');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Britany', 'O"Quinn', 1984  , 'Violinist');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Conner', 'Gardner', 1998 , 'Licensed Massage Therapist');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Mya', 'Austin', 1960  , 'Parquet Floor Layer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Thierry', 'Rogers', 2004  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Eloise', 'Rogers', 1984  , 'Computer Security Manager');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Gerard', 'Jackson', 1979 , 'Oil Exploration Engineer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Randy', 'Day', 1986 , 'Aircraft Electrician');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Jodie', 'Page', 1990 , 'Manufacturing Director');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Coral', '	Rice', 1996 , 'Window Washer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Ayman', 'Austin', 2002 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Jaxson', 'Austin', 1999  , 'Repair Worker');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Joel', 'Austin', 1973  , 'Police Officer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Alina', 'Austin', 2010  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Elin', 'Austin', 1962 , 'Payroll Clerk');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Ophelia', 'Wolf', 2004 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Eliot', 'McGuire', 1967  , 'Dentist');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Peter', 'McKinney', 1968 , 'Professor');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Annabella', 'Henry', 1974 , 'Nurse');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Anastasia', '	Baker', 2001  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Tyler', 'Baker', 1984  , 'Police Officer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Lilian', 'Ross', 1983  , 'Insurance Agent');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Thierry', 'Arnold', 1975  , 'Bus Driver');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Angelina', 'Rowe', 1979 , 'Firefighter');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Marcia', 'Rowe', 1974  , 'Health Educator');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Martin', 'Rowe', 1976  , 'Ship Engineer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Adeline', 'Rowe', 2005  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Colette', 'Rowe', 1963  , 'Professor');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Diane', 'Clark', 1975  , 'Payroll Clerk');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Caroline', 'Clark', 1960 , 'Dentist');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Dalton', 'Clayton', 1982 , '	Police Officer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Steve', 'Clayton', 1990  , 'Bus Driver');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Melanie', 'Clayton', 1987  , 'Computer Engineer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Alana', 'Wilson', 2007 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Carson', 'Byrne', 1995 , '	Food Scientist');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Conrad', 'Byrne', 2007  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Ryan', '	Porter', 2008  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Elin', 'Porter', 1978  , 'Computer Programmer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Tyler', 'Harvey', 2007  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Arya', 'Harvey', 2008 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Serena', 'Harvey', 1978 , 'School Teacher');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Lilly', 'Franklin', 1976 , 'Doctor');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Mai', 'Franklin', 1994 , 'Dentist');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('John', 'Franklin', 1999 , 'Firefighter');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Judy', 'Franklin', 1995 , 'Firefighter');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Katy', '	Lloyd', 1992 , 'School Teacher');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Tamara', 'Allen', 1963 , 'Ship Engineer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Maxim', 'Lyons', 1985 , 'Police Officer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Allan', 'Lyons', 1983 , 'Computer Engineer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Marc', 'Harris', 1980 , 'School Teacher');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Elin', 'Young', 2009 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Diana', 'Young', 2008 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Diane', 'Young', 2006 , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Alana', 'Bird', 2003  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Anna', 'Becker', 1979  , 'Security Agent');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Katie', 'Grant', 1977 , 'Manager');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Joan', 'Grant', 2010  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Bryan', 'Bell', 2001  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Belle', 'Miller', 1970  , 'Professor');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Peggy', 'Stevens', 1990  , 'Bus Driver');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Steve', 'Williamson', 1975 , 'HR Clerk');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Tyler', 'Williamson', 1999  , 'Doctor');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Izabelle', 'Williamson', 1990  , 'Systems Analyst');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Annabel', 'Williamson', 1960 , 'Cashier');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Mohamed', 'Waters', 1966 , 'Insurance Agent');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Marion', 'Newman', 1970  , 'Computer Programmer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Ada', 'Williams', 1986 , 'Computer Programmer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Sean', 'Scott', 1983  , 'Bus Driver');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Farrah', 'Scott', 1974  , 'Ship Engineer');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Christine', 'Lambert', 1973 , 'School Teacher');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Alysha', 'Lambert', 2007  , 'Student');
INSERT INTO Clients (ClientFirstName, ClientLastName, ClientDOB, Occupation) values ('Maia', 'Grant', 1984 , 'School Teacher');
